### ISSUE TITLE
Optimization suggestion: Increase button border

### ISSUE THREAD

**Issue by GuangChen2333** [leaf2006/EMUL#2]
Add a 1px black border on the button
like this:
```
border-style: solid;
border-width: 1px;
```
I think it looks good

**Comment by leaf2006** [comment]
Hmmmm...Ok,Let me check it now,thanks

**Comment by leaf2006** [comment]
Do you mean... Add this style attribute to all solid buttons?

**Comment by GuangChen2333** [comment]
I'm so sorry i didn't make myself clear，only red and yellow

**Comment by leaf2006** [comment]
Red and yellow?Ok,let me try

**Comment by GuangChen2333** [comment]
### Tested it in snapshot version
(I reply to myself)
